server:
  port: 8084

spring:
  application:
    name: API-Gateway
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: http://localhost:8081
          predicates:
            - Path=/user/**

        - id: JOB-SERVICE
          uri: http://localhost:8082
          predicates:
            - Path=/jobs/**

        - id: USER_JOB_MAPPING SERVICE
          uri: http://localhost:8083
          predicates:
            - Path=/userjobmapping/**
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

